import LinkedList from './LinkedList'

const myLinkedList = new LinkedList()
console.log('Empty?', myLinkedList.empty())
myLinkedList.push_front(50)
myLinkedList.push_front(40)
myLinkedList.push_front(30)
myLinkedList.push_front(20)
myLinkedList.push_front(10)
myLinkedList.push_front(5)
console.log(myLinkedList.toString())

console.log('Pop Front node', myLinkedList.pop_front())
console.log(myLinkedList.toString())
console.log('Empty?', myLinkedList.empty())
console.log('Size: ', myLinkedList.size())
console.log('Value at 3: ', myLinkedList.value_at(3))
console.log(myLinkedList.toString())
myLinkedList.push_back(60)
console.log(myLinkedList.toString())