import LinkedList from './LinkedList'

const myLinkedList = new LinkedList()
console.log('Empty?', myLinkedList.empty())
myLinkedList.push_front(50)
myLinkedList.push_front(40)
myLinkedList.push_front(30)
myLinkedList.push_front(20)
myLinkedList.push_front(10)
myLinkedList.push_front(5)
console.log(myLinkedList.toString())

console.log('Pop Front node', myLinkedList.pop_front())
console.log(myLinkedList.toString())
console.log('Empty?', myLinkedList.empty())
console.log('Size: ', myLinkedList.size())
console.log('Value at 3: ', myLinkedList.value_at(3))
console.log(myLinkedList.toString())
myLinkedList.push_back(60)
console.log(myLinkedList.toString())
console.log(myLinkedList.pop_back())
console.log(myLinkedList.toString())
console.log('Front node value:', myLinkedList.front())
console.log('Back node value: ', myLinkedList.back())
console.log(myLinkedList.toString())
console.log('Inserting at index 3', 35)
myLinkedList.insert(3, 35)
console.log('Inserting at index 0', 5)
myLinkedList.insert(0, 5)
console.log(myLinkedList.toString())
console.log('Erasing at 4')
myLinkedList.erase(4)
console.log('Erasing at 0')
myLinkedList.erase(0)
console.log(myLinkedList.toString())
console.log('Removing value 10')
myLinkedList.remove_value(10)
console.log(myLinkedList.toString())